// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/lightlog.cmd.proto

/*
Package lightlog is a generated protocol buffer package.

It is generated from these files:
	protos/lightlog.cmd.proto

It has these top-level messages:
	Cmd
*/
package lightlog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cmd struct {
	Cmd       string `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	StartTime int64  `protobuf:"varint,2,opt,name=startTime" json:"startTime,omitempty"`
	EndTime   int64  `protobuf:"varint,3,opt,name=endTime" json:"endTime,omitempty"`
}

func (m *Cmd) Reset()                    { *m = Cmd{} }
func (m *Cmd) String() string            { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()               {}
func (*Cmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Cmd) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *Cmd) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Cmd) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Cmd)(nil), "lightlog.cmd")
}

func init() { proto.RegisterFile("protos/lightlog.cmd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0xc9, 0x4c, 0xcf, 0x28, 0xc9, 0xc9, 0x4f, 0xd7, 0x4b, 0xce, 0x4d, 0xd1,
	0x03, 0x8b, 0x09, 0x71, 0xc0, 0xc4, 0x94, 0xfc, 0xb9, 0x98, 0x93, 0x73, 0x53, 0x84, 0x04, 0xc0,
	0x94, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x58, 0x44, 0x86, 0x8b, 0xb3, 0xb8, 0x24, 0xb1,
	0xa8, 0x24, 0x24, 0x33, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x39, 0x08, 0x21, 0x20, 0x24,
	0xc1, 0xc5, 0x9e, 0x9a, 0x97, 0x02, 0x96, 0x63, 0x06, 0xcb, 0xc1, 0xb8, 0x49, 0x6c, 0x60, 0x1b,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0x37, 0x23, 0x18, 0x7e, 0x00, 0x00, 0x00,
}
